# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]

jobs:
  os-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build and test
        run: |
          mvn -B package --file pom.xml
      - name: Upload test results for review
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results-${{ matrix.os }}
          path: |
            target/build.log
          retention-days: 5
  maven-version-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mvn: ['3.8.6', '3.6.3']
        java: ['11']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Set up maven wrapper for specified version
        run: |
          mvn wrapper:wrapper -Dmaven=${{ matrix.mvn }}
      - name: Build and test
        run: |
          mvn -B package --file pom.xml
      - name: Upload test results for review
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results-mvn-v${{ matrix.mvn }}-jvm${{ matrix.java }}
          path: |
            target/build.log
          retention-days: 5
